// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void forms() {
    driver.get("https://demoqa.com/");
    driver.manage().window().setSize(new Dimension(1920, 1053));
    driver.findElement(By.cssSelector(".card:nth-child(2) svg")).click();
    driver.findElement(By.cssSelector(".show .text")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Iovana");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Miranda");
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("test@test.bi.com.gt");
    driver.findElement(By.cssSelector(".custom-radio:nth-child(2) > .custom-control-label")).click();
    driver.findElement(By.id("userNumber")).click();
    driver.findElement(By.id("userNumber")).sendKeys("1234567890");
    driver.findElement(By.id("dateOfBirthInput")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      dropdown.findElement(By.xpath("//option[. = 'July']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      dropdown.findElement(By.xpath("//option[. = '1998']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".react-datepicker__day--028:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
    driver.findElement(By.id("react-select-2-option-0")).click();
    driver.findElement(By.cssSelector(".custom-checkbox:nth-child(3) > .custom-control-label")).click();
    driver.findElement(By.id("uploadPicture")).click();
    driver.findElement(By.id("uploadPicture")).sendKeys("C:\\fakepath\\prueba.txt");
    driver.findElement(By.id("currentAddress")).click();
    driver.findElement(By.id("currentAddress")).sendKeys("Banco Industrial Zona 4. 7a. Avenida 5-10, Zona 4 Centro Financiero Torre I");
    driver.findElement(By.cssSelector(".css-1gtu0rj-indicatorContainer > .css-19bqh2r")).click();
    driver.findElement(By.id("react-select-3-option-0")).click();
    driver.findElement(By.cssSelector(".css-1gtu0rj-indicatorContainer > .css-19bqh2r")).click();
    driver.findElement(By.id("react-select-4-option-0")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("closeLargeModal")).click();
  }
}
