// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TableTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void table() {
    driver.get("https://demoqa.com/");
    driver.manage().window().setSize(new Dimension(1920, 1053));
    driver.findElement(By.cssSelector(".card:nth-child(1) svg")).click();
    driver.findElement(By.id("item-3")).click();
    driver.findElement(By.cssSelector("#delete-record-1 path")).click();
    driver.findElement(By.id("addNewRecordButton")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Juan");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Perez");
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("test@test.bi.com.gt");
    driver.findElement(By.id("age")).click();
    driver.findElement(By.id("age")).sendKeys("24");
    driver.findElement(By.id("salary")).click();
    driver.findElement(By.id("salary")).sendKeys("8000");
    driver.findElement(By.id("department")).click();
    driver.findElement(By.id("department")).sendKeys("Guatemala");
    driver.findElement(By.id("submit")).click();
  }
}
